class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'app_title': 'Context-Aware AAC',
      'settings': 'Settings',
      'preferences': 'Preferences',
      'onboarding_title': 'Let\'s set things up',
      'next': 'Next',
      'back': 'Back',
      'skip': 'Skip',
      'skip_all': 'Skip All',
      'finish': 'Finish setup',
      'save': 'Save',
      'cancel': 'Cancel',
      'say_it': 'Say it',
      'write_own': 'None, write my own message',
      'write_own_title': 'Write your own reply',
      'auto_reply_on': 'Auto-reply is ON',
      'auto_reply_warning': 'The app will respond for you automatically. Turn this off in Settings if you want to choose replies yourself.',
      'mic_unavailable': 'Microphone/speech recognition unavailable.',
      'mic_hint': 'What did the other person say?',
      'hi': 'Hi',
      'source_phrasebook': 'From your usual replies',
      'source_either_or': 'Detected choice',
      'source_yes_no': 'Yes/No',
      'source_pref': 'Based on your preference',
      'source_llm': 'AI suggestion',
      'source_custom': 'Your own message',
      'type_either_or': 'Either/or question',
      'type_yes_no': 'Yes/No question',
      'type_known': 'Recognized question',
      'type_open': 'Open-ended (using AI)',
      'auto_reply_mode': 'Auto-reply mode',
      'auto_reply_sub': 'Not recommended: the app replies for you automatically without confirmation.',
      'ui_lang': 'App Interface Language',
      'pref_protein': 'Preferred protein',
      'pref_drink': 'Preferred drink',
      'cat_food': 'Food & Drink',
      'cat_lifestyle': 'Lifestyle',
      'cat_context': 'Context',
      'onboarding_name': 'What should we call you?',
      'step': 'Step',
      'of': 'of',
      'theme_mode': 'Theme Mode',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'theme_hc': 'High Contrast',
      'ai_active': 'AI Active',
      'powered_by': 'Powered by',
      'my_reply_hint': 'Type your own reply here...',
      'send': 'Send',
      'how_it_works': 'How it works',
      'fast_path_title': 'Instant Replies (Fast Path)',
      'fast_path_desc': 'For common questions (Yes/No, either/or, and learned phrases), the app works instantly and completely offline on your device.',
      'offline_title': 'Fully Offline-First',
      'offline_desc': 'Once the app learns your preferences and common phrases, it doesn\'t need an internet connection to help you communicate.',
      'ai_fallback_title': 'Smart Fallback (Slow Path)',
      'ai_fallback_desc': 'For new or complex sentences, the app securely uses advanced AI models to suggest natural replies.',
      'privacy_title': 'Your Privacy Matters',
      'privacy_desc': 'Your personal preferences and conversation history stay private on your device. Only the current sentence is sent to the AI for suggestions.',
      'select_ai': 'Select AI Model',
      'select_ai_desc': 'Choose which AI engine you want to use for smart suggestions.',
      'audio_mic': 'Audio & Microphone',
      'mic_status': 'Microphone Status',
      'mic_ready': 'Microphone Detected',
      'mic_not_ready': 'No Microphone Detected',
      'test_mic': 'Test Microphone',
      'stop_test': 'Stop Test',
      'volume_level': 'Input Volume',
      'mic_permission_denied': 'Microphone permission required for speech recognition.',
      'open_settings': 'Open Settings',
    },
    'ar': {
      'app_title': 'تواصل ذكي',
      'settings': 'الإعدادات',
      'preferences': 'التفضيلات',
      'onboarding_title': 'دعنا نجهز التطبيق',
      'next': 'التالي',
      'back': 'رجوع',
      'skip': 'تخطي',
      'skip_all': 'تخطي الكل',
      'finish': 'إنهاء الإعداد',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'say_it': 'تحدث',
      'write_own': 'لا شيء، سأكتب رسالتي الخاصة',
      'write_own_title': 'اكتب ردك الخاص',
      'auto_reply_on': 'الرد التلقائي مفعل',
      'auto_reply_warning': 'سيقوم التطبيق بالرد بدلاً منك تلقائياً. قم بإيقاف هذه الميزة من الإعدادات إذا كنت تريد اختيار الردود بنفسك.',
      'mic_unavailable': 'الميكروفون أو التعرف على الكلام غير متاح.',
      'mic_hint': 'ماذا قال الشخص الآخر؟',
      'hi': 'أهلاً',
      'source_phrasebook': 'من ردودك المعتادة',
      'source_either_or': 'خيار مكتشف',
      'source_yes_no': 'نعم/لا',
      'source_pref': 'بناءً على تفضيلاتك',
      'source_llm': 'اقتراح ذكي',
      'source_custom': 'رسالتك الخاصة',
      'type_either_or': 'سؤال خياري',
      'type_yes_no': 'سؤال نعم/لا',
      'type_known': 'سؤال معروف',
      'type_open': 'سؤال مفتوح (باستخدام الذكاء الاصطناعي)',
      'auto_reply_mode': 'وضع الرد التلقائي',
      'auto_reply_sub': 'غير مستحسن: يقوم التطبيق بالرد بدلاً منك تلقائياً دون تأكيد.',
      'ui_lang': 'لغة واجهة التطبيق',
      'pref_protein': 'البروتين المفضل',
      'pref_drink': 'المشروب المفضل',
      'cat_food': 'الطعام والشراب',
      'cat_lifestyle': 'نمط الحياة',
      'cat_context': 'السياق العام',
      'onboarding_name': 'بماذا ناديك؟',
      'step': 'خطوة',
      'of': 'من',
      'theme_mode': 'وضع المظهر',
      'theme_light': 'فاتح',
      'theme_dark': 'داكن',
      'theme_hc': 'تباين عالٍ',
      'ai_active': 'الذكاء الاصطناعي مفعل',
      'powered_by': 'بواسطة',
      'my_reply_hint': 'اكتب ردك هنا مباشرة...',
      'send': 'إرسال',
      'how_it_works': 'كيف يعمل التطبيق',
      'fast_path_title': 'ردود فورية (المسار السريع)',
      'fast_path_desc': 'للأسئلة الشائعة والعبارات التي تعلمها التطبيق، يعمل النظام فوراً وبدون إنترنت تماماً على جهازك.',
      'offline_title': 'يعمل بدون إنترنت',
      'offline_desc': 'بمجرد أن يتعلم التطبيق تفضيلاتك وعباراتك المعتادة، لن تحتاج إلى اتصال بالإنترنت للتواصل.',
      'ai_fallback_title': 'دعم ذكي (المسار الشامل)',
      'ai_fallback_desc': 'للجمل الجديدة أو المعقدة، يستخدم التطبيق نماذج ذكاء اصطناعي متطورة لاقتراح ردود طبيعية.',
      'privacy_title': 'خصوصيتك تهمنا',
      'privacy_desc': 'تظل تفضيلاتك الشخصية وسجل محادثاتك خاصة على جهازك. يتم إرسال الجملة الحالية فقط للذكاء الاصطناعي للحصول على اقتراحات.',
      'select_ai': 'اختر نموذج الذكاء الاصطناعي',
      'select_ai_desc': 'اختر محرك الذكاء الاصطناعي الذي تفضله للحصول على اقتراحات ذكية.',
      'audio_mic': 'الصوت والميكروفون',
      'mic_status': 'حالة الميكروفون',
      'mic_ready': 'تم اكتشاف الميكروفون',
      'mic_not_ready': 'لم يتم اكتشاف ميكروفون',
      'test_mic': 'اختبار الميكروفون',
      'stop_test': 'إيقاف الاختبار',
      'volume_level': 'مستوى الصوت',
      'mic_permission_denied': 'الإذن بالميكروفون مطلوب للتعرف على الكلام.',
      'open_settings': 'افتح الإعدادات',
    },
  };

  static String get(String key, String lang) {
    return _strings[lang]?[key] ?? _strings['en']?[key] ?? key;
  }
}
